### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users'

### ISSUE THREAD

**Issue by ZiShengCong** [RoosterBrother/AIYOU#1]
![fbb5f9d2837878c20624b98b17315698](https://github.com/RoosterBrother/AIYOU/assets/55382920/6e3c664f-a3e6-47bc-b907-e2add5dbc4db)
我的系统盘符是I，请问是这个原因吗？

**Comment by Cey1anze** [comment]
修改AppData目录下config.json中的modDownload路径为任意一个存在的路径
