### ISSUE TITLE
抽卡记录无法获取

### ISSUE THREAD

**Issue by xuanshao-zty** [RoosterBrother/AIYOU#2]
按使用方法点击获取还是提示找不到抽卡历史URL

**Comment by Cey1anze** [comment]
国服游戏吗> 按使用方法点击获取还是提示找不到抽卡历史URL

**Comment by Cey1anze** [comment]
> 按使用方法点击获取还是提示找不到抽卡历史URL

国服游戏吗

**Comment by xuanshao-zty** [comment]
> > 按使用方法点击获取还是提示找不到抽卡历史URL
> 
> 国服游戏吗

国际服的，无法使用吗？

**Comment by Cey1anze** [comment]
> > > 按使用方法点击获取还是提示找不到抽卡历史URL
> > 
> > 
> > 国服游戏吗
> 
> 国际服的，无法使用吗？

在游戏中打开抽卡历史，然后提供一下Wuthering Waves\Wuthering Waves Game\Client\Saved\Logs\Client.log给我

**Comment by xuanshao-zty** [comment]
[Client.log](https://github.com/user-attachments/files/16241925/Client.log)

**Comment by Cey1anze** [comment]
关掉游戏，删除Client.log，重新登陆游戏，打开抽卡历史，等待抽卡历史完全加载，像这样。
![image](https://github.com/user-attachments/assets/3e074a45-3df6-4ff7-bf69-4ea483e16a2b)
将Client.log提供给我

**Comment by xuanshao-zty** [comment]
[Client.log](https://github.com/user-attachments/files/16242060/Client.log)

**Comment by Cey1anze** [comment]
> [Client.log](https://github.com/user-attachments/files/16242060/Client.log)

你的log里面没有记录抽卡历史链接，后续更新会尝试使用其他方式获取
